### ISSUE TITLE
crash index out of bounds

### ISSUE THREAD

**Issue by kohlhase** [slatex/stextools#48]
i am getting the following errors from time to time: 
```
 | File 9/36       | Annotations added: 14     |
                                                            /Users/kohlhase/localmh/MathHub/courses/FAU/IWGS/course/source/progintro/sec/jupyterlab.en.tex                                                            
   1 \documentclass[notes]{notesslides}
   2 \libinput{course-preamble}
   3 \begin{document}
   4 \usemodule[smglom/IWGS]{mod?jupyterNB}
   5 \tociftopnotes 
   6 \begin{sfragment}[id=sec.jupyterlab]{\Sn{jupyterLab}, a Python Web IDE for IWGS}
   7   \inputref{progintro/slides/jupyterLab.en}
   8   \inputref*[courses/Jacobs/GenICT/course]{python/snip/hello-intro.en}
   9   \inputref{progintro/slides/helloworld.en}
  10   \inputref{progintro/slides/jupyterNotebooks.en}
  11   \inputref[courses/Jacobs/TDM/course]{digdocs/slides/markdown.en}
  12 \end{sfragment}

Commands:   enter h (help) to see all available commands
  [h]elp
  [q]uit
  [s]kip once
  [0] ✓ smglom/computing mod?web-IDE?web IDE
  [1] ✗ courses/FAU/IWGS/course progintro/slides?pythonanywhere?web IDE
>>> 0
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/kohlhase/vc/git/github.com/sLaTeX/stextools/stextools/__main__.py", line 96, in <module>
    cli()
    ~~~^^
  File "/Users/kohlhase/vc/git/github.com/sLaTeX/stextools/.venv/lib/python3.13/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/Users/kohlhase/vc/git/github.com/sLaTeX/stextools/.venv/lib/python3.13/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/Users/kohlhase/vc/git/github.com/sLaTeX/stextools/.venv/lib/python3.13/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/kohlhase/vc/git/github.com/sLaTeX/stextools/.venv/lib/python3.13/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kohlhase/vc/git/github.com/sLaTeX/stextools/.venv/lib/python3.13/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/Users/kohlhase/vc/git/github.com/sLaTeX/stextools/stextools/__main__.py", line 92, in srify
    srify(files, filter, ignore)
    ~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kohlhase/vc/git/github.com/sLaTeX/stextools/stextools/srify/controller.py", line 373, in srify
    unfinished = controller.run()
  File "/Users/kohlhase/vc/git/github.com/sLaTeX/stextools/stextools/srify/controller.py", line 180, in run
    if not self.ensure_cursor_selection():
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/kohlhase/vc/git/github.com/sLaTeX/stextools/stextools/srify/controller.py", line 304, in ensure_cursor_selection
    selection_cursor = self.find_next_selection()
  File "/Users/kohlhase/vc/git/github.com/sLaTeX/stextools/stextools/srify/controller.py", line 332, in find_next_selection
    lstrs = get_linked_strings(text)
  File "/Users/kohlhase/vc/git/github.com/sLaTeX/stextools/stextools/srify/selection.py", line 70, in get_linked_strings
    _recurse(walker.get_latex_nodes()[0])
    ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kohlhase/vc/git/github.com/sLaTeX/stextools/stextools/srify/selection.py", line 61, in _recurse
    _recurse(node.nodelist)
    ~~~~~~~~^^^^^^^^^^^^^^^
  File "/Users/kohlhase/vc/git/github.com/sLaTeX/stextools/stextools/srify/selection.py", line 61, in _recurse
    _recurse(node.nodelist)
    ~~~~~~~~^^^^^^^^^^^^^^^
  File "/Users/kohlhase/vc/git/github.com/sLaTeX/stextools/stextools/srify/selection.py", line 61, in _recurse
    _recurse(node.nodelist)
    ~~~~~~~~^^^^^^^^^^^^^^^
  [Previous line repeated 2 more times]
  File "/Users/kohlhase/vc/git/github.com/sLaTeX/stextools/stextools/srify/selection.py", line 52, in _recurse
    _recurse([node.nodeargs[arg_idx]])
              ~~~~~~~~~~~~~^^^^^^^^^
IndexError: list index out of range
kohlhase@faui8-pool2 notes % 

```

**Comment by jfschaefer** [comment]
It's hard to debug this.
I've created a better error message (to give me more useful information) and allow the user to just skip the problematic part.

**Comment by kohlhase** [comment]
I will keep this in mind and report any future error messages here.
