### ISSUE TITLE
error

### ISSUE THREAD

**Issue by kohlhase** [slatex/stextools#57]
I get the following error: 
```

 | File 23/259     | Annotations added: 2      |
                            /Users/kohlhase/localmh/MathHub/smglom/computing/source/mod/RustLanguage.en.tex                             
   4 \begin{smodule}[title={Rust (Programming Language)}]{RustLanguage}
   5 \importmodule{mod?program}
   6 \textsymdecl{RustLanguage}[type=\sn{programming language}]{Rust}
   7       
   8 \begin{sdefinition}
   9   \definiendum{RustLanguage}\RustLanguage is a system-near \sn{programming language} with
  10   a strong focus on memory safety.
  11 \end{sdefinition}
  12 \end{smodule}
  13 \end{document}
  14 %%% Local Variables:
  15 %%% mode: latex
  16 %%% TeX-master: t

Commands:   enter h (help) to see all available commands
  [h]elp
  [q]uit
  [s]kip once
  [0] ✗ smglom/computing mod?memory?memory
  [1] ✗ smglom/cogsci mod?memory?memory
>>> 0
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/kohlhase/vc/git/github.com/sLaTeX/stextools/stextools/__main__.py", line 96, in <module>
    cli()
    ~~~^^
  File "/Users/kohlhase/vc/git/github.com/sLaTeX/stextools/.venv/lib/python3.13/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/Users/kohlhase/vc/git/github.com/sLaTeX/stextools/.venv/lib/python3.13/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/Users/kohlhase/vc/git/github.com/sLaTeX/stextools/.venv/lib/python3.13/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/kohlhase/vc/git/github.com/sLaTeX/stextools/.venv/lib/python3.13/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kohlhase/vc/git/github.com/sLaTeX/stextools/.venv/lib/python3.13/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/Users/kohlhase/vc/git/github.com/sLaTeX/stextools/stextools/__main__.py", line 92, in srify
    srify(files, filter, ignore)
    ~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kohlhase/vc/git/github.com/sLaTeX/stextools/stextools/srify/controller.py", line 470, in srify
    unfinished = controller.run()
  File "/Users/kohlhase/vc/git/github.com/sLaTeX/stextools/stextools/srify/controller.py", line 241, in run
    outcomes = self._get_and_run_command()
  File "/Users/kohlhase/vc/git/github.com/sLaTeX/stextools/stextools/srify/controller.py", line 332, in _get_and_run_command
    return command_collection.apply(state=self.state)
           ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/Users/kohlhase/vc/git/github.com/sLaTeX/stextools/stextools/srify/commands.py", line 404, in apply
    return command.execute(state=state, call=call)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kohlhase/vc/git/github.com/sLaTeX/stextools/stextools/srify/annotate_command.py", line 258, in execute
    return self.get_outcome_for_symbol(symbol)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "/Users/kohlhase/vc/git/github.com/sLaTeX/stextools/stextools/srify/annotate_command.py", line 222, in get_outcome_for_symbol
    import_thing = self.get_import(symbol)
  File "/Users/kohlhase/vc/git/github.com/sLaTeX/stextools/stextools/srify/annotate_command.py", line 47, in get_import
    import_locations = self.get_import_locations()
  File "/Users/kohlhase/vc/git/github.com/sLaTeX/stextools/stextools/srify/annotate_command.py", line 183, in get_import_locations
    _recurse(LatexWalker(self.state.get_current_file_text(), latex_context=STEX_CONTEXT_DB).get_latex_nodes()[0])
    ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kohlhase/vc/git/github.com/sLaTeX/stextools/stextools/srify/annotate_command.py", line 177, in _recurse
    _recurse(node.nodelist)
    ~~~~~~~~^^^^^^^^^^^^^^^
  File "/Users/kohlhase/vc/git/github.com/sLaTeX/stextools/stextools/srify/annotate_command.py", line 177, in _recurse
    _recurse(node.nodelist)
    ~~~~~~~~^^^^^^^^^^^^^^^
  File "/Users/kohlhase/vc/git/github.com/sLaTeX/stextools/stextools/srify/annotate_command.py", line 177, in _recurse
    _recurse(node.nodelist)
    ~~~~~~~~^^^^^^^^^^^^^^^
  File "/Users/kohlhase/vc/git/github.com/sLaTeX/stextools/stextools/srify/annotate_command.py", line 163, in _recurse
    _recurse(node.nodeargd.argnlist)
    ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kohlhase/vc/git/github.com/sLaTeX/stextools/stextools/srify/annotate_command.py", line 163, in _recurse
    _recurse(node.nodeargd.argnlist)
             ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'argnlist'
kohlhase@faui8-pool2 mod % 
```

**Comment by kohlhase** [comment]
Another occurrence? 
```


 | File 9/15       | Annotations added: 13     |
                                                                            /Users/kohlhase/localmh/MathHub/smglom/mv/source/mod/mv.en.tex                                                                            
  34 \symdecl*{mathematical vernacular}
  35 \symdecl*{math idiom}
  36 \symdecl*{iff}
  37 
  38 \begin{sdefinition}[id=math-vernacular.def,for={nexisS,nexis,uexisS,uexis,exisS,exis,foral,foralS,
  39   imply,negate,conj,disj,biimpl,foralst,exisst}]
  40   \Sns{mathematician} use a stylized language that
  41   \begin{itemize}
  42   \item uses \sns{expression?expression} (also called
  43     \definiendum{expression?expression}{formulae}) to represent \sn{mathematical}
  44     objects.
  45   \item uses \definiendum{math idiom}{math idioms} for special situations (e.g. \sn{iff},
  46     \textbf{hence}, \textbf{let\ldots be\ldots, then\ldots})

Commands:   enter h (help) to see all available commands
  [h]elp
  [q]uit
  [s]kip once
  [0] ✗ smglom/computing mod?program?programming language
  [1] ✓ smglom/sets mod?formal-language?formal language
  [2] ✓ smglom/linguistics mod?natural-language?natural language
  [3] ✓ smglom/grammar mod?grammar-language?language
  [4] ✗ smglom/grammar mod?word-language-generated-by-grammar?language
  [5] ✗ smglom/linguistics mod?jargon?jargon
  [6] ✗ smglom/grammar mod?type0-type1-type2-type3-languages?context-free language
  [7] ✗ smglom/theocs mod?regular-set?regular
  [8] ✗ smglom/theocs mod?TM-Langacceptor?language of
  [9] ✗ smglom/theocs mod?word-language-accepted-DFA?language
  [10] ✗ smglom/theocs mod?word-language-accepted-NFA?language
  [11] ✗ smglom/theocs mod?word-language-ENFA?language
  [12] ✗ smglom/theocs mod?language-PDA?language
  [13] ✗ smglom/logic mod/logical-system?logical-system/logsys-module?language
  [14] ✗ courses/Jacobs/ACS/course fa/slides/nutshell-ex?fa-nutshell?language
>>> 5
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/kohlhase/vc/git/github.com/sLaTeX/stextools/stextools/__main__.py", line 96, in <module>
    cli()
    ~~~^^
  File "/Users/kohlhase/vc/git/github.com/sLaTeX/stextools/.venv/lib/python3.13/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/Users/kohlhase/vc/git/github.com/sLaTeX/stextools/.venv/lib/python3.13/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/Users/kohlhase/vc/git/github.com/sLaTeX/stextools/.venv/lib/python3.13/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/kohlhase/vc/git/github.com/sLaTeX/stextools/.venv/lib/python3.13/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kohlhase/vc/git/github.com/sLaTeX/stextools/.venv/lib/python3.13/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/Users/kohlhase/vc/git/github.com/sLaTeX/stextools/stextools/__main__.py", line 92, in srify
    srify(files, filter, ignore)
    ~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kohlhase/vc/git/github.com/sLaTeX/stextools/stextools/srify/controller.py", line 470, in srify
    unfinished = controller.run()
  File "/Users/kohlhase/vc/git/github.com/sLaTeX/stextools/stextools/srify/controller.py", line 241, in run
    outcomes = self._get_and_run_command()
  File "/Users/kohlhase/vc/git/github.com/sLaTeX/stextools/stextools/srify/controller.py", line 332, in _get_and_run_command
    return command_collection.apply(state=self.state)
           ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/Users/kohlhase/vc/git/github.com/sLaTeX/stextools/stextools/srify/commands.py", line 404, in apply
    return command.execute(state=state, call=call)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kohlhase/vc/git/github.com/sLaTeX/stextools/stextools/srify/annotate_command.py", line 258, in execute
    return self.get_outcome_for_symbol(symbol)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "/Users/kohlhase/vc/git/github.com/sLaTeX/stextools/stextools/srify/annotate_command.py", line 222, in get_outcome_for_symbol
    import_thing = self.get_import(symbol)
  File "/Users/kohlhase/vc/git/github.com/sLaTeX/stextools/stextools/srify/annotate_command.py", line 47, in get_import
    import_locations = self.get_import_locations()
  File "/Users/kohlhase/vc/git/github.com/sLaTeX/stextools/stextools/srify/annotate_command.py", line 183, in get_import_locations
    _recurse(LatexWalker(self.state.get_current_file_text(), latex_context=STEX_CONTEXT_DB).get_latex_nodes()[0])
    ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kohlhase/vc/git/github.com/sLaTeX/stextools/stextools/srify/annotate_command.py", line 177, in _recurse
    _recurse(node.nodelist)
    ~~~~~~~~^^^^^^^^^^^^^^^
  File "/Users/kohlhase/vc/git/github.com/sLaTeX/stextools/stextools/srify/annotate_command.py", line 177, in _recurse
    _recurse(node.nodelist)
    ~~~~~~~~^^^^^^^^^^^^^^^
  File "/Users/kohlhase/vc/git/github.com/sLaTeX/stextools/stextools/srify/annotate_command.py", line 163, in _recurse
    _recurse(node.nodeargd.argnlist)
    ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kohlhase/vc/git/github.com/sLaTeX/stextools/stextools/srify/annotate_command.py", line 165, in _recurse
    _recurse(node.nodelist)
    ~~~~~~~~^^^^^^^^^^^^^^^
  File "/Users/kohlhase/vc/git/github.com/sLaTeX/stextools/stextools/srify/annotate_command.py", line 165, in _recurse
    _recurse(node.nodelist)
    ~~~~~~~~^^^^^^^^^^^^^^^
  File "/Users/kohlhase/vc/git/github.com/sLaTeX/stextools/stextools/srify/annotate_command.py", line 163, in _recurse
    _recurse(node.nodeargd.argnlist)
    ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kohlhase/vc/git/github.com/sLaTeX/stextools/stextools/srify/annotate_command.py", line 163, in _recurse
    _recurse(node.nodeargd.argnlist)
             ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'argnlist'
kohlhase@faui8-pool2 mod % 
```
