### ISSUE TITLE
`snify` errors about subpaths

### ISSUE THREAD

**Issue by lambdaTotoro** [slatex/stextools#62]
Currently, I am facing a problem with getting `snify` to work. After installing it as documented, I called it via `python3 -m stextools snify emoji_modifiers.en.tex` in the directory `/home/totoro/localmh/MathHub/courses/FAU/IWGS/problems/source/general/quiz` on my local machine (FreeBSD). This produced an error (see below).

I _do_ have both a directory `problems` and a directory `problems-private` in `.../courses/FAU/IWGS`, but I absolutely, positively did call the program in the `problems` directory. The git in this directory is on the private branch and Michael assured me this is not a problem that exists for him.

I'm working with the current (as of this morning @ 11AM) version.

What follows is the complete output (printouts for progress reporting removed) with the error message:
```
INFO:stextools.core.cache:The cache appears to come from an older version of stextools. Clearing it...
INFO:stextools.core.cache:No MathHub info found in cache - I will start from scratch.
INFO:stextools.core.mathhub:Scanning archives...
INFO:stextools.core.mathhub:Found 115 MathHub archives
INFO:stextools.core.mathhub:Updating the information for 12905 files
INFO:stextools.core.mathhub:Processed 1/12905 files
INFO:stextools.core.mathhub:Processed 31/12905 files
[...]
INFO:stextools.core.mathhub:Processed 12841/12905 files
INFO:stextools.core.mathhub:Finished updating the information
INFO:stextools.core.cache:Writing MathHub info to cache...
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/totoro/Development/FAU/vc/github.com/sLaTeX/stextools/stextools/__main__.py", line 97, in <module>
    cli()
  File "/home/totoro/.local/lib/python3.9/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/totoro/.local/lib/python3.9/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/totoro/.local/lib/python3.9/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/totoro/.local/lib/python3.9/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/totoro/.local/lib/python3.9/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/totoro/Development/FAU/vc/github.com/sLaTeX/stextools/stextools/__main__.py", line 93, in snify_actual
    snify(files, filter, ignore)
  File "/home/totoro/Development/FAU/vc/github.com/sLaTeX/stextools/stextools/snify/controller.py", line 477, in snify
    controller = Controller(state, new_files=[Path(file).absolute().resolve() for file in files])
  File "/home/totoro/Development/FAU/vc/github.com/sLaTeX/stextools/stextools/snify/controller.py", line 165, in __init__
    self.load_files_dialog(new_files)
  File "/home/totoro/Development/FAU/vc/github.com/sLaTeX/stextools/stextools/snify/controller.py", line 170, in load_files_dialog
    stexdoc = self.mh.get_stex_doc(file)
  File "/home/totoro/Development/FAU/vc/github.com/sLaTeX/stextools/stextools/core/mathhub.py", line 52, in get_stex_doc
    return repo.get_stex_doc(path.relative_to(repo.path).as_posix())
  File "/usr/local/lib/python3.9/pathlib.py", line 939, in relative_to
    raise ValueError("{!r} is not in the subpath of {!r}"
ValueError: '/home/totoro/localmh/MathHub/courses/FAU/IWGS/problems/source/general/quiz/emoji_modifiers.en.tex' is not in the subpath of '/home/totoro/localmh/MathHub/courses/FAU/IWGS/problems-private' OR one path is relative and the other is absolute.
```

Any idea what could be the problem here?

**Comment by kohlhase** [comment]
Jonas, do you really need both? Is this just a leftover from the old setup? 
You can switch branches. 
Just deleting the private repository should "fix" the problem.
