### ISSUE TITLE
crash when undoing

### ISSUE THREAD

**Issue by kohlhase** [slatex/stextools#68]
I had used the editor `e` to fix a typo, and then tried to use `u` to get the focus back into sync. That lead to the following crash. 
```
| File 2/6        | Annotations added: 12     |
                                  /Users/kohlhase/localmh/MathHub/courses/FAU/LBS/problems/source/nlfrags/quiz/why-functions.en.tex                                   
  11   In $\FragmentThree$ we need a \sr{logical system}{target logic} that can handle
  12   (\sr{higher-order function}{higher-order}) \sr{higher-order function}{functions},
  13   because
  14   \begin{mcb}
  15     \mcc[T]{The \sns{denotation} of \sns{verb phrase} are \sns{mod?predicate?predicate}, i.e. \sns{function} to \sns{mod?truthvalues?truth value}}
  16     \mcc[T]{The \sns{denotation} of \sn{verb phrase} \sr{coordinator}{connectives} have to be \sr{second-order function}{functionals}}
  17     \mcc{\Sns{function} can transform  \sns{phrase} of any syntactical category into any others}
  18     \mcc{Functional programming is better than logic programming for implementing NLU systems.}
  19   \end{mcb}    
  20 \end{sproblem}
  21 \end{document}
  22 
  23 %%% Local Variables:

Commands:   enter h (help) to see all available commands
  [h]elp
  [q]uit
  [0] ✗ courses/FAU/AI/course nlp/slides?text-classification?text classification
  [s]kip once
>>> u
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/kohlhase/vc/git/github.com/sLaTeX/stextools/stextools/__main__.py", line 103, in <module>
    cli()
    ~~~^^
  File "/Users/kohlhase/vc/git/github.com/sLaTeX/stextools/.venv/lib/python3.13/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/Users/kohlhase/vc/git/github.com/sLaTeX/stextools/.venv/lib/python3.13/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/Users/kohlhase/vc/git/github.com/sLaTeX/stextools/.venv/lib/python3.13/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/kohlhase/vc/git/github.com/sLaTeX/stextools/.venv/lib/python3.13/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kohlhase/vc/git/github.com/sLaTeX/stextools/.venv/lib/python3.13/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/Users/kohlhase/vc/git/github.com/sLaTeX/stextools/stextools/__main__.py", line 99, in snify_actual
    snify(files, filter, ignore)
    ~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kohlhase/vc/git/github.com/sLaTeX/stextools/stextools/snify/controller.py", line 493, in snify
    unfinished = controller.run()
  File "/Users/kohlhase/vc/git/github.com/sLaTeX/stextools/stextools/snify/controller.py", line 291, in run
    mod.unapply(self.state)
    ~~~~~~~~~~~^^^^^^^^^^^^
  File "/Users/kohlhase/vc/git/github.com/sLaTeX/stextools/stextools/snify/controller.py", line 58, in unapply
    raise RuntimeError(f"File {self.file} has been modified since the last time it was written")
RuntimeError: File /Users/kohlhase/localmh/MathHub/courses/FAU/LBS/problems/source/nlfrags/quiz/why-functions.en.tex has been modified since the last time it was written
kohlhase@faui8-pool2 quizzes % 
```

**Comment by jfschaefer** [comment]
I've fixed #69 
Undoing file modifications when the file has been edited is tricky (hence the error).
I've changed it so that it doesn't crash anymore in this situation and instead prints errors.
